spring:
  application:
    name: gateway-service
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration

  cloud:
    gateway:
      routes:
        - id: crypto-analyzer
          uri: http://crypto-analyzer:8080
          predicates:
            - Path=/crypto/**
        - id: file-upload
          uri: http://crypto-analyzer:8080
          predicates:
            - Path=/data/**
        - id: swagger
          uri: http://crypto-analyzer:8080
          predicates:
            - Path=/swagger-ui/**
        - id: v3
          uri: http://crypto-analyzer:8080
          predicates:
            - Path=/v3/api-docs/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            DEBUG
        boot:
          autoconfigure:
            security: INFO
        security: DEBUG
        web: DEBUG
        data: DEBUG
#logging:
#  level:
#    org:
#      springframework:
#        cloud:
#          gateway: DEBUG
#        boot:
#          autoconfigure:
#            security: INFO

server:
  port: 8080
